---
title: "MEM Fluxes"
author: "James R Holmquist"
date: "5/21/2020"
output: pdf_document
---

```{r setup, include=TRUE}

require(rCTM)
require(tidyverse)
require(gridExtra)

```

``` {r graph MEM-CTM output}
# First we'll profile the script
start_time <- Sys.time()
memCohortExample <- runMemWithCohorts(startYear=2015, rslrT1=0.3, rslrTotal=100,
                                      initElv=21.9, MSL=7.4, MHW=16.9, MHHW=25.4, MHHWS=31.2, 
                                      ssc=3e-05, lunarNodalAmp=2.5, bMax=0.25, 
                                      zVegMin=-24.7, zVegMax=44.4, zVegPeak=22.1,
                                      plantElevationType="orthometric", rootToShoot=2,
                                      rootTurnover=0.5, rootDepthMax=30, omDecayRate=0.8,
                                      recalcitrantFrac=0.2, settlingVelocity=2.8,
                                      coreYear = 2050)
print(Sys.time()-start_time)
```

```{r functionsForDeterminingFluxes}

omToOcParams <- list(B=0,
                     B1=0.42)

salinity <- 3

salThreshold <- 14
salRate <- 0.5

salinityPlot <- 1:32 

maxCH4effect <- 1

salEffect <- maxCH4effect/(1+exp(salRate*(salinityPlot-salThreshold)))

plot(x=salinityPlot, y=salEffect, type = "l",
     xlab = "salinity (ppt)",
     ylab = "Salinity effect")

```

``` {r memOutputsToFluxes}

# Going to write a function that takes MEM outputs and pareses the fluxes into CO2 and CH4
memOutputsToFluxes <- function(cohorts, annualTimeSteps, 
                               omToOcParams = list(B=0, B1=0.42),
                               salinity = 32,
                               salThreshold = 14,
                               salRate = 0.5,
                               maxCH4effect = 1) {
  
  # To convert OM to OC
  # If parmeter list is 2 long then simple linear correlation
  if (length(omToOcParams) == 2) {
    omToOc <- function(om, B=omToOcParams$B, B1=omToOcParams$B1) {return(B + om*B1)}
  } else if (length(omToOcParams) == 3) {
    # If parameter list is 3 long, then it's quadratic
    omToOc <- function(om, B=omToOcParams$B, B1=omToOcParams$B1,
                       B2=omToOcParams$B2) {return(B + om*B1 + om^2*B2)}
  } else {
    # If something else then trip an error message
    stop("Invalid number of organic matter to organic carbon conversion parameters,")
  }
  
  # If one single salinity value is entered add it to the annual time steps table all
  # If multiple salinity values are entered, add to the annual time step table,
  # as long as they are the same lenght. 
  # If mutliple values are entered, but not the same number of years of the scenario, trip an error.
  if (length(salinity == 1) | length(salinity) == nrow(annualTimeSteps)) {
    annualTimeSteps <- dplyr::mutate(annualTimeSteps, salinity = salinity)
  } else {
    stop("Invalid entry for salinities, either one single value, or one for each year of the simulation.")
  }
  
  # Create a table of tidal cycles
  highTidesPerYear <- 352.657
  higherHighTidesPerYear <- 352.657 - 24.72
  springTidesPerYear <- 24.72
  hoursInTidalCycle <- 12.42
  
  tidalCycles <- data.frame(datum = c("MHW", "MHHW", "MHHWS"),
                            nTides = c(highTidesPerYear, higherHighTidesPerYear, springTidesPerYear),
                            stringsAsFactors = F)
  
  timeStepsRelevantData <- annualTimeSteps %>% 
    dplyr::select(years, MSL, matches("MHW|MHHW|MHHWS"), surfaceElevation, salinity) %>% 
    rename(year=years) %>% 
    tidyr::gather(key = "datum", value = "datumHigh",
                  -year, -MSL, -surfaceElevation, -salinity) %>% 
    dplyr::mutate(datumLow = MSL-(datumHigh-MSL)) %>% 
    dplyr::left_join(tidalCycles) %>% 
    dplyr::arrange(year, datum) # not really necessary
    
  C_to_CH4 <- 16.04 / 12.01
  C_to_CO2 <- 44.01 / 12.01
  
  ghgFluxesCohorts <- cohorts %>% 
    select(year, age, respired_OM, layer_top, layer_bottom) %>% 
    # Join the Surface Elevation, MSL, MHW, MHHW, and MHHWS, 
    # and salinity data from annual time steps to cohorts
    dplyr::full_join(timeStepsRelevantData) %>% 
    # Calculate fractional inundation time for each cohort
    dplyr::mutate(layer_mid = layer_bottom - ((layer_bottom-layer_top)/2),
                  z = surfaceElevation - layer_mid,
      floodTime = ifelse(z > datumHigh,
                         0, floodTimeFromDatum(z = z, datumHigh = datumHigh,
                                               datumLow = datumLow) * nTides)) %>%
    dplyr::select(year, age, layer_top, layer_bottom, layer_mid, respired_OM, salinity, floodTime) %>% 
    dplyr::group_by(year, age, layer_top, layer_bottom, layer_mid, respired_OM, salinity) %>% 
    dplyr::summarise(floodTime = sum(floodTime)) %>% 
    dplyr::mutate(floodFraction = floodTime / 8760,
                  respired_C = omToOc(respired_OM),
                  salinity_effect = maxCH4effect / (1+exp(salRate*(salinity-salThreshold))),
                  respired_C_CH4 = respired_C * floodFraction * salinity_effect,
                  respired_C_CO2 = respired_C - respired_C_CH4,
                  respired_CH4 = respired_C_CH4 * C_to_CH4,
                  respired_CO2 = respired_C_CO2 * C_to_CO2)
  
  # Each cohorts outgoing C in CH4 is a function of
  # Inundation time and whether sulfates turn methane production on or off
  # Each cohort's outgoing C in CO2 is the inverse
  # Convert C to CH4
  # Convert C to CO2
  
  ghgFluxesAnnual <- ghgFluxesCohorts %>% 
    dplyr::group_by(year) %>% 
    dplyr::summarise(respired_CH4 = sum(respired_CH4), # Summarise each years CH4 emission
              respired_CO2 = sum(respired_CO2)) # Summarise each year's CO2 respiration
  
  co2_removal <- cohorts %>% 
    dplyr::group_by(year) %>% 
    dplyr::summarise(slow_OM = sum(slow_OM)) %>% 
    dplyr::mutate(slow_OM_change = slow_OM - lag(slow_OM),
                  sequestered_C = -omToOc(slow_OM_change),
                  sequestered_CO2 = sequestered_C * C_to_CO2) %>% 
    select(year, sequestered_CO2)
  
  
  ghgFluxesAnnual <- dplyr::left_join(ghgFluxesAnnual, co2_removal,
                                      by=c("year"))
    
  return(list(ghgFluxesCohorts, ghgFluxesAnnual))
  
  }

ghgFluxesAnnual <- memOutputsToFluxes(cohorts = memCohortExample$cohorts,
                                      annualTimeSteps = memCohortExample$annualTimeSteps,
                                      salinity=3)

ghgFluxesAnnualPlot <- ghgFluxesAnnual[[2]] %>%
  gather(value = "flux", key = "gas", -year) %>% 
  # bind_rows(co2_removal_plot) %>% 
  mutate(flux = flux * 10000)

ggplot(data = ghgFluxesAnnualPlot, aes(x=year, y=flux, color = gas)) +
  geom_line() +
  geom_point() +
  ylab(expression(paste("flux (g m"^"-2", " yr"^"-1", ")")))

ggsave("../../../Desktop/MEM_CH4_Attempt_Flux_200522.jpg",
       width=4,
       height=3)

subsetOfYears <- seq(min(ghgFluxesAnnual[[1]]$year),
                     max(ghgFluxesAnnual[[1]]$year),
                     4)
ghgFluxesCohortsPlot <- filter(ghgFluxesAnnual[[1]],
                               year %in% subsetOfYears)

ggplot(ghgFluxesCohortsPlot, aes(x=layer_mid, y=respired_CH4)) +
  geom_line(aes(color = as.character(year)), alpha=0.6) +
  coord_flip() +
  scale_x_reverse() +
  xlab("Profile Depth (cm)") +
  ylab(expression(paste("CH"[4], " Flux (g cm"^"-2", " yr"^"-1", ")")))

ggsave("../../../Desktop/MEM_CH4_DepthSeries_200522.jpg",
       width=4,
       height=3)

```
