---
title: "Function dependencies and conventions"
author: "K Todd-Brown (ktoddbrown@ufl.edu)"
date: "5/27/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plyr)
library(dplyr)
library(rCTM)
library(DiagrammeR)
```

```{r pullFunctionNames}

packageFunctionName <- ls(getNamespace("rCTM"))
functionRegExp <- paste0('(', packageFunctionName, ')', collapse = '|')

allfunctions <- plyr::adply(packageFunctionName, c(1), function(xx){
  ##print(xx)
  fileLines <- read_lines(file=list.files(path = '../R', pattern = xx, full.names = TRUE))
  functionLines <- body(xx)
  calledFunctions <- unique(unlist(regmatches(paste0(functionLines, collapse= ';'), 
                                gregexpr(functionRegExp, paste0(functionLines, collapse= ';')))))
  
  if(length(calledFunctions) > 0){
    ans <- data.frame(parent_name = xx,
                      type='called',
                      child_name = calledFunctions, stringsAsFactors = FALSE)
  }else{
    ans <- data.frame()
  }
  suggestedFunctions <- unique(unlist(
    regmatches(paste0(fileLines, collapse= ';'), 
               gregexpr(functionRegExp, paste0(fileLines, collapse= ';')))
  ))
  
  suggestedFunctions <- setdiff(suggestedFunctions, c(unique(calledFunctions), xx))
  
  if(length(suggestedFunctions) > 0){
    ans <- rbind(ans, data.frame(parent_name = xx,
                                 type='suggested',
                                 child_name = suggestedFunctions,
                                 stringsAsFactors = FALSE))
    
  }
  return(ans)
})


inputVariable <- plyr::ldply(setNames(packageFunctionName, packageFunctionName),function(xx){
  return(data.frame(function_name = xx, 
                    argument = formalArgs(xx), 
                    defaults = as.character(formals(xx)), stringsAsFactors = FALSE))
                    })
```

```{r}
as.tibble(allfunctions)

as.tibble(inputVariable)

```
```{r}
nodeList <- paste0(sprintf('%s [label = %s]', packageFunctionName, packageFunctionName), collapse ='; ')
edgeList <- paste(allfunctions$child_name, allfunctions$parent_name, sep='->', collapse = ' ')

grViz(sprintf("
              digraph function_dependencies{
              
              graph [overlap = true, fontsize = 10]
              
              node [shape = 'box']
              %s
              
              #edges
              %s
              
              }", nodeList, edgeList))
```

```{r}
inputVariable %>% arrange(argument)
```