---
title: "Examples of cohort and march equlibrium models"
author: "K Todd-Brown (ktoddbrown@gmail.com)"
date: "Spring 2019"
output: 
  html_document: 
    toc: yes
---

# Set up
```{r setUp}
library(tidyverse)

##Uncomment to install from the github repo
#library(devtools)
#install_github("tilbud/MEMs")

library(MEMs)

##Debug option
#walk(list.files('../R', full.names = TRUE), source)

defaultParms <- list(rootDepthMax = 30, # Depth of the root zone in cm below surface
                     totalRootBiomass = 0.3, # 0.3 Total Root Biomass, g/cm2
                     rootTurnover = 0.5,  # Below Ground Turnover Rate of roots, 1/yr
                     rootOmFrac = list(fast=0.8, slow=0.2), # root allocation to om pools (labile, slow), g/g
                     omDecayRate = list(fast=0.8, slow=0), # organic matter decay rate (labile, slow), 1/yr
                     ssc = 20, # Suspended Sediment Concentration, mg per liter
                     depthBelowMHW = 10) # Depth of Marsh Surface Below Mean High Water

defaultConsts <- list(soilLength = 1, soilWidth = 1, #assume a 1x1 cm2 area
                      shape='linear', #root mass distribution
                      packing = list(root = 0.085, #density of roots g-C/cm3
                                     organic = 0.085 ,  # Organic Self Packing Densities: k1 g-C/cm3
                                     mineral = 1.99), # Inorganic Self Packing Densities  k2 g-C/cm3
                      nTidesPerYear = 704, #number of high tides per year
                      sedimentInputType = c('constant', 'relative', 'dynamic')[1],
                      modernAge = NA) #max age in modern soil profile

```

## Test root profile
```{r functionRootProfile}
##Check liveRoots
testRoots <- massLiveRoots(layerBottom = seq(5, 40, by=5), layerTop=seq(0, 35, by=5),
                    totalRootMass_per_area = defaultParms$totalRootBiomass,
                    rootDepthMax=defaultParms$rootDepthMax)
plot(x=1/2*(seq(5, 40, by=5) + seq(0, 35, by=5)), y=testRoots)

paste('Conservation of mass is: ', sum(testRoots) - defaultParms$totalRootBiomass*defaultConsts$soilLength*defaultConsts$soilWidth < 1e-5)
```

## Test depth of given soil volume
```{r functionFindVol}
##Check depth of non root volue
testDepth <- depthOfNotRootVolume(nonRootVolume = 1:100,
                                  totalRootMass_per_area = defaultParms$totalRootBiomass,
                                  rootDepthMax=defaultParms$rootDepthMax,
                                  rootDensity = defaultConsts$packing$root)
plot(testDepth)
plot(testDepth[1:99] - testDepth[2:100])
```

## Sediment input
```{r functionSedIn}
#constant input of sediment
defaultSedIn <- sedimentInputs(ssc = defaultParms$ssc, # Suspended Sediment Concentration, mg per liter
               meanTidalHeight = defaultParms$depthBelowMHW #mean tide height above marsh
               )

#constant sea level try 31.74 for default marshElevation
#depthBelowMHW <- max(0, consts$meanHighWaterElevation - marshElevation)

#raising sea level
#depthBelowMHW <- max(0, (31.74 + 0.03 * yrForward) - marshElevation)

paste('Sediment input rate with default parameters: ', defaultSedIn, ' g yr-1')
```

## Step soil profile forward

```{r functionStepCohort}
startingProfile <- data.frame(age=NA, fast_OM=NA, slow_OM=NA, mineral=NA, root_mass=NA,
                              layer_top=NA, layer_bottom=NA)

for(ii in 1:100){
  startingProfile <- addCohort(massPools = startingProfile,
                               rootTurnover = defaultParms$rootTurnover, 
                               rootOmFrac = defaultParms$rootOmFrac,
                               omDecayRate = defaultParms$omDecayRate,
                               packing = defaultConsts$packing,
                               
                               mineralInput_g_per_yr.fn = sedimentInputs,
                               ssc = defaultParms$ssc, 
                               meanTidalHeight = defaultParms$depthBelowMHW, 
                               
                               massLiveRoots.fn = massLiveRoots,
                               totalRootMass_per_area = defaultParms$totalRootBiomass,
                               rootDepthMax=defaultParms$rootDepthMax,
                               
                               depthOfNotRootVolume.fn = depthOfNotRootVolume,
                               rootDensity = defaultConsts$packing$root
                               #totalRootMass_per_area, 
                               #  rootDepthMax,
                               )
}
```

# Plot equlibrium profiles

```{r runMEM}

tick <- Sys.time()
equProfile <- runToEquilibrium(rootTurnover = defaultParms$rootTurnover, 
                               rootOmFrac = defaultParms$rootOmFrac,
                               omDecayRate = defaultParms$omDecayRate,
                               packing = defaultConsts$packing,
                               
                               mineralInput_g_per_yr.fn = sedimentInputs,
                               ssc = defaultParms$ssc, 
                               meanTidalHeight = defaultParms$depthBelowMHW, 
                               
                               massLiveRoots.fn = massLiveRoots,
                               totalRootMass_per_area = defaultParms$totalRootBiomass,
                               rootDepthMax = defaultParms$rootDepthMax,
                               
                               depthOfNotRootVolume.fn = depthOfNotRootVolume,
                               rootDensity = defaultConsts$packing$root)
tock <- Sys.time() - tick
print(tock)

ggplot(equProfile %>%
         gather(key='variable', value='value', -layer_top, -layer_bottom)) +
  geom_line(aes(x=(layer_top+layer_bottom)/2, y=value)) +
  facet_wrap(~variable, scales='free')

ggplot(equProfile) +
  geom_line(aes(x=(layer_top+layer_bottom)/2, y=layer_bottom - layer_top))

```

```{r runWithNoIn}
nonInputProfile <- equProfile

for(ii in 1:100){
    noInputProfile <- addCohort(massPools = noInputProfile,
                               rootTurnover = defaultParms$rootTurnover, 
                               rootOmFrac = defaultParms$rootOmFrac,
                               omDecayRate = defaultParms$omDecayRate,
                               packing = defaultConsts$packing,
                               
                               mineralInput_g_per_yr.fn = (function(...)0), #set 0 inputs
                               
                               massLiveRoots.fn = massLiveRoots,
                               totalRootMass_per_area = defaultParms$totalRootBiomass,
                               rootDepthMax=defaultParms$rootDepthMax,
                               
                               depthOfNotRootVolume.fn = depthOfNotRootVolume,
                               rootDensity = defaultConsts$packing$root)
  
}

ggplot(noInputProfile %>%
         gather(key='variable', value='value', -layer_top, -layer_bottom)) +
  geom_line(aes(x=(layer_top+layer_bottom)/2, y=value)) +
  geom_line(data=equProfile %>%
         gather(key='variable', value='value', -layer_top, -layer_bottom),
         aes(x=(layer_top+layer_bottom)/2, y=value), color='grey') +
  labs(title='Equlibrium (grey) vs 100yr no input (black)') +
  facet_wrap(~variable, scales='free')

```


# Run marsh forward under steady and raising sea levels
```{r steadySealevel}
steadySeaProfile <- equProfile
raisingSeaProfile <- equProfile

startingElevation <- max(equProfile$layer_bottom)

profileDepth <- data.frame(year = 0:100,
                     steadySea=c(startingElevation, rep(NA, 100)),
                     raisingSea=c(startingElevation, rep(NA, 100)))

for(ii in 1:100){
  steadySeaProfile <- addCohort(massPools = steadySeaProfile,
                               rootTurnover = defaultParms$rootTurnover, 
                               rootOmFrac = defaultParms$rootOmFrac,
                               omDecayRate = defaultParms$omDecayRate,
                               packing = defaultConsts$packing,
                               
                               mineralInput_g_per_yr.fn = sedimentInputs,
                               ssc = defaultParms$ssc, 
                               meanTidalHeight = defaultParms$depthBelowMHW + startingElevation -
                                 max(steadySeaProfile$layer_bottom, na.rm=TRUE),
                               
                               massLiveRoots.fn = massLiveRoots,
                               totalRootMass_per_area = defaultParms$totalRootBiomass,
                               rootDepthMax=defaultParms$rootDepthMax,
                               
                               depthOfNotRootVolume.fn = depthOfNotRootVolume,
                               rootDensity = defaultConsts$packing$root)
  
  raisingSeaProfile <- addCohort(massPools = raisingSeaProfile,
                               rootTurnover = defaultParms$rootTurnover, 
                               rootOmFrac = defaultParms$rootOmFrac,
                               omDecayRate = defaultParms$omDecayRate,
                               packing = defaultConsts$packing,
                               
                               mineralInput_g_per_yr.fn = sedimentInputs,
                               ssc = defaultParms$ssc, 
                               meanTidalHeight = defaultParms$depthBelowMHW+0.03*ii + 
                                 startingElevation -
                                 max(steadySeaProfile$layer_bottom, na.rm=TRUE),
                               
                               massLiveRoots.fn = massLiveRoots,
                               totalRootMass_per_area = defaultParms$totalRootBiomass,
                               rootDepthMax=defaultParms$rootDepthMax,
                               
                               depthOfNotRootVolume.fn = depthOfNotRootVolume,
                               rootDensity = defaultConsts$packing$root) 

  profileDepth$steadySea[ii+1] <- max(steadySeaProfile$layer_bottom)
  profileDepth$raisingSea[ii+1] <- max(raisingSeaProfile$layer_bottom)
}

```


```{r}

print(sprintf('Change in marsh elevation after 100 years with no change in sea level is %.4f cm, and with a 0.03 cm/yr raise in sea level %.4f cm', max(steadySeaProfile$layer_bottom) - startingElevation, 
              max(raisingSeaProfile$layer_bottom) - startingElevation))

ggplot(profileDepth %>% gather(key='type', value='max. profile depth [cm]', steadySea, raisingSea)) +
         geom_line(aes(x=year, y=`max. profile depth [cm]`, color=type))

ggplot(profileDepth %>%
         mutate(`changeInElev_steadySea` = c(steadySea[2:length(year)] - steadySea[1:(length(year) - 1)], NA),
                `changeInElev_raisingSea` = c(raisingSea[2:length(year)] - raisingSea[1:(length(year) - 1)], NA)) %>%
         gather(key='type', value='change in elevation [cm yr-1]', starts_with('changeInElev'))) +
         geom_line(aes(x=year, y=`change in elevation [cm yr-1]`, color=type))

plot.df <- bind_rows(startingProfile %>% mutate(type='inital'),
                     steadySeaProfile %>% mutate(type='steady seas'),
                     raisingSeaProfile %>% mutate(type='raising seas'))

ggplot(plot.df) +
  geom_line(aes(x=(layer_top+layer_bottom)/2, y=age, color=type)) 

ggplot(plot.df) +
  geom_line(aes(x=(layer_top+layer_bottom)/2, y=fast_OM+slow_OM, color=type)) 
```

# Example converting cohort to uniform depth

```{r convertToUnifDepth}
equProfile <- equProfile[is.finite(equProfile$age),]
sampleStep<- 5
profile_by_depth <- data.frame(top = seq(0, floor(max(equProfile$layer_top) - sampleStep),
                                         by=sampleStep), 
           bottom = seq(sampleStep, floor(max(equProfile$layer_top)), by=sampleStep)) %>%
  group_by(top, bottom) %>%
  mutate(age = weighted.mean(equProfile$age, 
                             pmax(pmin(equProfile$layer_bottom, bottom) - 
                                    pmax(equProfile$layer_top, top), 0)),
         fast_OM = sum(equProfile$fast_OM *
                             pmax(pmin(equProfile$layer_bottom, bottom) - 
                                    pmax(equProfile$layer_top, top), 0) / 
                         (equProfile$layer_bottom - equProfile$layer_top)),
         slow_OM = sum(equProfile$slow_OM * 
                             pmax(pmin(equProfile$layer_bottom, bottom) - 
                                    pmax(equProfile$layer_top, top), 0) / 
                         (equProfile$layer_bottom - equProfile$layer_top)),
         mineral = sum(equProfile$mineral* 
                             pmax(pmin(equProfile$layer_bottom, bottom) - 
                                    pmax(equProfile$layer_top, top), 0) / 
                         (equProfile$layer_bottom - equProfile$layer_top)),
         root = sum(equProfile$root_mass * 
                             pmax(pmin(equProfile$layer_bottom, bottom) - 
                                    pmax(equProfile$layer_top, top), 0) / 
                         (equProfile$layer_bottom - equProfile$layer_top)),
         soil_volume = sum((equProfile$cumCohortVol - 
                        c(0, equProfile$cumCohortVol[-length(equProfile$cumCohortVol)])) * 
                             pmax(pmin(equProfile$layer_bottom, bottom) - 
                                    pmax(equProfile$layer_top, top), 0) / 
                         (equProfile$layer_bottom - equProfile$layer_top))) %>%
  mutate(bulk_density = sum(fast_OM+slow_OM+mineral)/soil_volume) %>%
  mutate(SOM = sum(fast_OM+slow_OM)/bulk_density)

ggplot(profile_by_depth) +
  geom_line(aes(x=(top+bottom)/2, y=age)) +
  geom_line(data=equProfile, aes(x=(layer_top+layer_bottom)/2, y=age), color='yellow', linetype=3)

ggplot(profile_by_depth %>%
         gather(key='variable', value='value', SOM, bulk_density, fast_OM, slow_OM, mineral)) +
  geom_line(aes(x=(top+bottom)/2, y=value)) +
  facet_wrap(~variable, scales = 'free_y')
```

## Parameter exploration run

```{r parameterRuns}
parametersToRun <- expand.grid(rootDepthMax=c(15, 30, 60), 
            totalRootBiomass=c(0.15, 0.3, 0.6),
            rootTurnover=c(0.25, 0.5, 0.9),
            rootOmFrac_fast=c(0.2, 0.4, 0.8),
            omDecayRate_fast=c(0.2, 0.4, 0.8),
            ssc=c(10, 20, 40),
            depthBelowMHW=c(5, 10, 20)) %>%
  filter(rootDepthMax*defaultConsts$packing$root/2 >
           totalRootBiomass) %>% #check that we don't have above a max biomass per area
  sample_n(size=60) %>%
  #slice(c(20, 14, 93, 400, 3000, 12000, 10000)) %>% # nrow = 12 600
  mutate(index = 1:n()) %>%
  group_by_all() %>%
  do((function(xx){
    newParms <- list(rootDepthMax = xx$rootDepthMax, # Depth of the root zone in cm below surface
                     totalRootBiomass = xx$totalRootBiomass, # Total Root Biomass, g/cm2
                     rootTurnover = xx$rootTurnover,  # Below Ground Turnover Rate of roots, 1/yr
                     rootOmFrac = list(fast=xx$rootOmFrac_fast, 
                                       slow=1-xx$rootOmFrac_fast), # root allocation to om pools (labile, slow), g/g
                     omDecayRate = list(fast=xx$omDecayRate_fast, slow=0), # organic matter decay rate (labile, slow), 1/yr
                     ssc = xx$ssc, # Suspended Sediment Concentration, mg per liter
                     depthBelowMHW = xx$depthBelowMHW)
    return(runToEquilibrium(rootTurnover = newParms$rootTurnover, 
                            rootOmFrac = newParms$rootOmFrac,
                            omDecayRate = newParms$omDecayRate,
                            packing = defaultConsts$packing,
                            
                            mineralInput_g_per_yr.fn = sedimentInputs,
                            ssc = newParms$ssc, 
                            meanTidalHeight = newParms$depthBelowMHW, 
                            
                            massLiveRoots.fn = massLiveRoots,
                            totalRootMass_per_area = newParms$totalRootBiomass,
                            rootDepthMax = newParms$rootDepthMax,
                            
                            depthOfNotRootVolume.fn = depthOfNotRootVolume,
                            rootDensity = defaultConsts$packing$root, 
                            
                            maxAge=1000))
  })(.)) %>%
  mutate('Total OM [g]' = fast_OM + slow_OM,
         'Soil volume [cm3]' = (fast_OM + slow_OM) / defaultConsts$packing$organic +
                       mineral/defaultConsts$packing$mineral,
         'OM [g g-1]' = (fast_OM + slow_OM) / (fast_OM + slow_OM + mineral)) %>%
  mutate('SOM [g-OM cm-3]' = `Total OM [g]` / `Soil volume [cm3]`)


ggplot(parametersToRun %>%
         gather(key='variable', value='value', age:mineral, root_mass, `Total OM [g]`:`SOM [g-OM cm-3]`)) +
  geom_line(aes(x=(layer_top+layer_bottom)/2, y=value, group=index), alpha=0.3) +
  scale_y_log10() +
  facet_wrap(~variable, scales='free')
```


