---
title: "Getting closer to full blown MEM"
author: "James R Holmquist"
date: "3/14/2019"
output: html_document
---

``` {r setup annapolis inputs, include = F}
library(tidyverse)
library(zoo)
library(rCTM)

elvNAVD88 <- 0.2
MHWtoNAVD88 <- 0.25
MSLtoNAVD88 <- 0.09

bMax <- .2500
dVegMax <- .6
dVegMin <- -.1
zVegMax <- (dVegMax-MSLtoNAVD88) / (MHWtoNAVD88 - MSLtoNAVD88)
zVegMin <- (dVegMin-MSLtoNAVD88) / (MHWtoNAVD88 - MSLtoNAVD88)

rootToShoot <- 2

predictAgbFromElv <- function(x=0, MHWtoNAVD88=0.25, MSLtoNAVD88=0.09, 
                              bMax=.2500,
                              zVegMax=3.1875, zVegMin=-1.1875) {
  
  zInputElv <- (x-MSLtoNAVD88) / (MHWtoNAVD88 - MSLtoNAVD88)
  Dopt<-(zVegMax+zVegMin)/2
  
  a <- -((-zVegMin * bMax - zVegMax * bMax) / ((zVegMin - Dopt) * (-zVegMax + Dopt)))
  b <- -(bMax / ((zVegMin - Dopt) * (-zVegMax + Dopt)))
  c <- (zVegMin * zVegMax * bMax) / ((zVegMin - Dopt) * (zVegMax - Dopt))
  
  agb <- a*zInputElv + b*zInputElv^2 + c
  
  agb <- ifelse(agb>0,agb,0)
  
  return(agb)
  }

testParabola <- seq(-.2,.7,by=0.01)
testParabolaZ <- (testParabola - MSLtoNAVD88) / (MHWtoNAVD88 - MSLtoNAVD88)
testAGB <- mapply(x=testParabola, predictAgbFromElv)

storeTestParabola <- data.frame(testParabolaZ, testAGB)
plot(testParabolaZ, testAGB)

elvRandomEffect <- 1.1
elvYear <- 2013

annapolisTideGauge <- read_csv("sampleData/annapolisTideGauge.csv")

annapolisTideGaugeTimeSeries <- annapolisTideGauge %>%
  group_by(Year) %>%
  summarise(MHW = mean(MHW, na.rm = F), 
         MSL = mean(MSL, na.rm = F)) %>%
  select(Year, MHW, MSL) %>%
  mutate(MSL = na.approx(MSL),
    TidalRange = MHW-MSL)

annapolisTideGaugeTimeSeriesTall <- annapolisTideGaugeTimeSeries %>%
  select(Year, MHW, MSL) %>%
  gather(Datum, WaterLevel, c(MHW, MSL)) %>%
  arrange(Year, Datum)

initElv <- elvNAVD88 - ((annapolisTideGaugeTimeSeries$MSL[annapolisTideGaugeTimeSeries$Year == elvYear] -
  annapolisTideGaugeTimeSeries$MSL[1]) * elvRandomEffect)

initDepthBelowMHW <- annapolisTideGaugeTimeSeries$MHW[1] - initElv

initBiomass <- predictAgbFromElv(initElv, MHWtoNAVD88=annapolisTideGaugeTimeSeries$MHW[1],
                                 MSLtoNAVD88=annapolisTideGaugeTimeSeries$MSL[1])*rootToShoot

```

```{r setup CTM/MEM, include=FALSE}

defaultParms <- list(rootDepthMax = 45, # Depth of the root zone in cm below surface
                     totalRootBiomass = initBiomass, # 0.3 Total Root Biomass, g/cm2
                     rootTurnover = 2.5,  # Below Ground Turnover Rate of roots, 1/yr
                     rootOmFrac = list(fast=0.6, slow=0.4), # root allocation to om pools (labile, slow), g/g
                     omDecayRate = list(fast=0.8, slow=0), # organic matter decay rate (labile, slow), 1/yr
                     ssc = 30, # Suspended Sediment Concentration, mg per liter
                     depthBelowMHW = initDepthBelowMHW*100)  # Depth of Marsh Surface Below Mean High Water

defaultConsts <- list(soilLength = 1, soilWidth = 1, #assume a 1x1 cm2 area
                      shape='linear', #root mass distribution
                      packing = list(root = 0.085, #density of roots g-C/cm3
                                     organic = 0.085 ,  # Organic Self Packing Densities: k1 g-C/cm3
                                     mineral = 1.99), # Inorganic Self Packing Densities  k2 g-C/cm3
                      nTidesPerYear = 704, #number of high tides per year
                      sedimentInputType = c('constant', 'relative', 'dynamic')[1],
                      modernAge = NA) #max age in modern soil profile

#source('R/massLiveRoots.R')
#source('R/depthOfNonRootVolume.R')
##source('R/addCohort.R')
#source('R/sedimentInputs.R')
#source('R/addCohort.R')
#source('R/runToEquilibrium.R')

```

``` {r run sims, include = F}

# equProfile <- runToEquilibrium(consts = defaultConsts, parms=defaultParms)
# 
# raisingSeaProfile <- equProfile
# datum <- initElv
# profileWidthM <- max(equProfile$layer_bottom)/100
# 
# surfaceNavd <- initElv
# baselineNavd <- initElv - profileWidthM
# totalAccretion <- profileWidthM
# 
# for (i in 1:nrow(annapolisTideGaugeTimeSeries)) {
#   
#   meanTidalHeightAtTime <- annapolisTideGaugeTimeSeries$MHW[i] - surfaceNavd * 100
#   agbAtTime <- predictAgbFromElv(surfaceNavd, annapolisTideGaugeTimeSeries$MHW[i],
#                                  annapolisTideGaugeTimeSeries$MSL[i])*rootToShoot
#   
#   raisingSeaProfile <- addCohort(massPools = raisingSeaProfile,
#                                ssc = defaultParms$ssc, 
#                                 meanTidalHeight = meanTidalHeightAtTime, 
#                                 rootTurnover = defaultParms$rootTurnover, 
#                                 rootOmFrac = defaultParms$rootOmFrac,
#                                 omDecayRate = defaultParms$omDecayRate,
#                                 totalRootMass_per_area = agbAtTime, 
#                                 rootDepthMax = defaultParms$rootDepthMax,
#                                 consts = defaultConsts)
#   
#   tempStorage <- raisingSeaProfile %>%
#     mutate(organicMatter = (fast_OM+slow_OM+root_mass)/(fast_OM+slow_OM+root_mass+mineral),
#            Year = annapolisTideGaugeTimeSeries$Year[i],
#            layer_top=surfaceNavd-(layer_top/100),
#            layer_bottom=surfaceNavd-(layer_bottom/100))
#   
#   accretion <- max(raisingSeaProfile$layer_bottom)/100 - profileWidthM
#   profileWidthM <- max(raisingSeaProfile$layer_bottom)/100
#   surfaceNavd <- surfaceNavd + accretion
#     
#   if (i == 1) {
#     storeForAnimation <- tempStorage
#   } else {
#     storeForAnimation <- rbind(tempStorage, storeForAnimation)
#   }
# }


equProfile <- runToEquilibrium(consts = defaultConsts, parms=defaultParms)

raisingSeaProfile <- equProfile
datum <- initElv
profileWidthM <- max(equProfile$layer_bottom)/100

surfaceNavd <- initElv
baselineNavd <- initElv - profileWidthM
totalAccretion <- profileWidthM

store_ZstarAndAGB <- data.frame(Zstar = rep(NA, nrow(annapolisTideGaugeTimeSeries)),
                                AGB = rep(NA, nrow(annapolisTideGaugeTimeSeries)),
                                Year =annapolisTideGaugeTimeSeries$Year)

for (i in 1:nrow(annapolisTideGaugeTimeSeries)) {
  
  meanTidalHeightAtTime <- annapolisTideGaugeTimeSeries$MHW[i] - surfaceNavd * 100
  
  agbAtTime <- predictAgbFromElv(surfaceNavd, annapolisTideGaugeTimeSeries$MHW[i],
                                 annapolisTideGaugeTimeSeries$MSL[i])*rootToShoot
  
  store_ZstarAndAGB$Zstar[i] <- (surfaceNavd-annapolisTideGaugeTimeSeries$MSL[i]) /
    (annapolisTideGaugeTimeSeries$MHW[i]-annapolisTideGaugeTimeSeries$MSL[i])

  store_ZstarAndAGB$AGB[i]<-agbAtTime
  
  raisingSeaProfile <- addCohort(massPools = raisingSeaProfile,
                               ssc = defaultParms$ssc, 
                                meanTidalHeight = meanTidalHeightAtTime, 
                                rootTurnover = defaultParms$rootTurnover, 
                                rootOmFrac = defaultParms$rootOmFrac,
                                omDecayRate = defaultParms$omDecayRate,
                                totalRootMass_per_area = agbAtTime, 
                                rootDepthMax = defaultParms$rootDepthMax,
                                consts = defaultConsts)
  
  tempStorage <- raisingSeaProfile %>%
    mutate(organicMatter = (fast_OM+slow_OM+root_mass)/(fast_OM+slow_OM+root_mass+mineral),
           layer_top=surfaceNavd-(layer_top/100),
           layer_bottom=surfaceNavd-(layer_bottom/100))
  
  accretion <- max(raisingSeaProfile$layer_bottom)/100 - profileWidthM
  profileWidthM <- max(raisingSeaProfile$layer_bottom)/100
  surfaceNavd <- surfaceNavd + accretion

  age_depth <- tempStorage %>%
    select(age, layer_top, layer_bottom)
  
  mass_cohorts <- tempStorage %>%
    mutate(summed_mass = mineral + root_mass + fast_OM + slow_OM,
           mineral =  mineral / summed_mass,
           root_mass = root_mass / summed_mass,
           fast_OM = fast_OM / summed_mass,
           slow_OM = slow_OM / summed_mass) %>%
    select(age, mineral, root_mass, fast_OM, slow_OM) %>%
    rename("root mass" = root_mass,
           "fast pool OM" = fast_OM,
           "slow pool OM" = slow_OM) %>%
    gather(key = "mass_pool", value = "mass_fraction", -age) %>%
    filter(mass_fraction > 0) %>%
    arrange(age)
  
  x_min <- c()
  x_max <- c()
  
  for (j in 1:nrow(mass_cohorts)) {
    if (j == 1) {
      x_min <- c(x_min, 0)
      x_max <- c(x_max, mass_cohorts$mass_fraction[j])
    } else {
      if (mass_cohorts$age[j] != mass_cohorts$age[j-1]) {
        x_min <- c(x_min, 0)
        x_max <- c(x_max, mass_cohorts$mass_fraction[j])
      } else {
        x_min <- c(x_min, x_max[j-1])
        x_max <- c(x_max, x_max[j-1] + mass_cohorts$mass_fraction[j])
      }
    }
  }
  mass_cohorts$x_min <- x_min
  mass_cohorts$x_max <- x_max
  
  mass_cohorts_display <- mass_cohorts %>%
    left_join(age_depth) %>%
    mutate(Year = annapolisTideGaugeTimeSeries$Year[i]) %>%
    select(Year, age, mass_pool, layer_top, layer_bottom, x_min, x_max)

  if (i == 1) {
     storeForAnimation <- mass_cohorts_display
   } else {
     storeForAnimation <- rbind(mass_cohorts_display, storeForAnimation)
   }
 }
}

```

``` {r code, }
library(gganimate)
cbPalette <- c("#56B4E9", "#999999", "#E69F00", "#009E73")


display_cohorts <- ggplot(data = storeForAnimation, aes(xmin = x_min, xmax = x_max, ymin = layer_bottom, ymax = layer_top, frame = Year)) +
  geom_rect(aes(fill = mass_pool), color = rgb(0,0,0, alpha = 0.1)) +
  theme_minimal() +
  scale_fill_manual(values=cbPalette) +
  geom_hline(data=annapolisTideGaugeTimeSeriesTall, aes(yintercept=WaterLevel, lty=Datum), color="blue") +
  theme(axis.title.x=element_blank(),
    axis.text.x=element_blank(),
    axis.ticks.x=element_blank(),
    text = element_text(size=14),
    ) +
  ylab("Depth (m NAVD88)") +
  labs(title = 'Year: {round(frame_time,0)}',
       fill = "Mass Pools") +
  transition_time(Year) +
  ease_aes('linear')

animate(display_cohorts, duration = 30)
anim_save("temp/MEM-anim-mass-cohorts-190509.gif", width = 4, height = 8, units = "in", dpi = 300)

displayBiomassResponse <- ggplot(data = store_ZstarAndAGB, aes(x = Zstar, y=AGB, frame = Year)) +
  geom_line(data=storeTestParabola, aes(x=testParabolaZ, y=testAGB, frame=NA)) +
  geom_point(color="red") +
  transition_time(Year) +
  ease_aes('linear')
displayBiomassResponse



```

``` {r animate plot}
library(gganimate)
soil_profile <- ggplot(data = storeForAnimation, aes(xmin = 0, xmax = 1, ymin = layer_bottom, ymax = layer_top, frame = Year)) +
  geom_rect(aes(fill = organicMatter), color = rgb(0,0,0, alpha = 0.1)) +
  scale_fill_gradient2(low = "darkgrey", mid = "lightgrey", high = "darkgreen", midpoint = 0.13, name = "Organic Matter (fraction)") + 
  theme_minimal() +
  geom_hline(data=annapolisTideGaugeTimeSeriesTall, aes(yintercept=WaterLevel, lty=Datum), color="blue") +
  theme(axis.title.x=element_blank(),
    axis.text.x=element_blank(),
    axis.ticks.x=element_blank(),
    text = element_text(size=14),
    ) +
  ylab("Depth (m NAVD88)") +
  labs(title = 'Year: {round(frame_time,0)}') +
  transition_time(Year) +
  ease_aes('linear')

animate(soil_profile, duration = 30)

anim_save("temp/MEM-anim-190318.gif", width = 4, height = 8, units = "in", dpi = 300)




```